<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class protondex extends \ccxt\async\Exchange {
    public function public_get_markets_all($params = array()) {
        return $this->request('markets/all', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_orders_open($params = array()) {
        return $this->request('orders/open', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_orders_history($params = array()) {
        return $this->request('orders/history', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_orders_lifecycle($params = array()) {
        return $this->request('orders/lifecycle', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_orders_depth($params = array()) {
        return $this->request('orders/depth', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_trades_daily($params = array()) {
        return $this->request('trades/daily', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_trades_history($params = array()) {
        return $this->request('trades/history', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_trades_recent($params = array()) {
        return $this->request('trades/recent', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_chart_ohlcv($params = array()) {
        return $this->request('chart/ohlcv', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_status_sync($params = array()) {
        return $this->request('status/sync', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_account_balances($params = array()) {
        return $this->request('account/balances', 'public', 'GET', $params, null, null, array());
    }
    public function public_post_orders_serialize($params = array()) {
        return $this->request('orders/serialize', 'public', 'POST', $params, null, null, array());
    }
    public function public_post_orders_submit($params = array()) {
        return $this->request('orders/submit', 'public', 'POST', $params, null, null, array());
    }
    public function private_get_user_fees($params = array()) {
        return $this->request('user/fees', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_account_deposits($params = array()) {
        return $this->request('account/deposits', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_account_withdrawals($params = array()) {
        return $this->request('account/withdrawals', 'private', 'GET', $params, null, null, array());
    }
    public function publicGetMarketsAll($params = array()) {
        return $this->request('markets/all', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetOrdersOpen($params = array()) {
        return $this->request('orders/open', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetOrdersHistory($params = array()) {
        return $this->request('orders/history', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetOrdersLifecycle($params = array()) {
        return $this->request('orders/lifecycle', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetOrdersDepth($params = array()) {
        return $this->request('orders/depth', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetTradesDaily($params = array()) {
        return $this->request('trades/daily', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetTradesHistory($params = array()) {
        return $this->request('trades/history', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetTradesRecent($params = array()) {
        return $this->request('trades/recent', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetChartOhlcv($params = array()) {
        return $this->request('chart/ohlcv', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetStatusSync($params = array()) {
        return $this->request('status/sync', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetAccountBalances($params = array()) {
        return $this->request('account/balances', 'public', 'GET', $params, null, null, array());
    }
    public function publicPostOrdersSerialize($params = array()) {
        return $this->request('orders/serialize', 'public', 'POST', $params, null, null, array());
    }
    public function publicPostOrdersSubmit($params = array()) {
        return $this->request('orders/submit', 'public', 'POST', $params, null, null, array());
    }
    public function privateGetUserFees($params = array()) {
        return $this->request('user/fees', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetAccountDeposits($params = array()) {
        return $this->request('account/deposits', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetAccountWithdrawals($params = array()) {
        return $this->request('account/withdrawals', 'private', 'GET', $params, null, null, array());
    }
}
